baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "devil"

[params]
  author = "Demo Author"
  license = "GNU GPL"
  license_url = "/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Gallery"
url = "/gallery"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 6

[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto:mail@example.com"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/example"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/example"
